### ISSUE TITLE
Frameworks not found

### ISSUE THREAD

**Issue by wafisher** [caseyscarborough/keylogger#11]
Unfortunately, the Makefile isn't working for me. I got the following error at first:

`./keylogger.h:7:10: fatal error: 'ApplicationServices/ApplicationServices.h' file not found`

which turned into the following, after adding `-F/System/Library/Frameworks` to the `gcc` command:

`/System/Library/Frameworks/CoreServices.framework/Frameworks/OSServices.framework/Headers/CSIdentity.h:24:10: fatal error: 'MobileCoreServices/CSIdentityBase.h' file not found`

Any thoughts? Seems like it thinks I'm compiling for an iPhone per the lines near the error.

Thanks!

**Comment by caseyscarborough** [comment]
Interesting. I'm unable to reproduce this, actually the `/System/Library/Frameworks/CoreServices.framework/Frameworks/OSServices.framework/Headers/` directory doesn't exist for me either.

What version of Mac OS X are you running?

**Comment by wafisher** [comment]
10.11.5. But that Makefile is supposed to work _without_ specifying a location for system libraries, as I ended up doing?

**Comment by caseyscarborough** [comment]
Yes, that's correct... What about your gcc version? Here's my output from `gcc -v` if it helps:

```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by wafisher** [comment]
Same exact thing. It must be something different. I probably removed some file here or there — I'll figure it out and type up my answer when I do.

**Comment by wafisher** [comment]
Working now. Solved it by waiting 10 months. That solution may or may not work for others.
