### ISSUE TITLE
Does not record user/password

### ISSUE THREAD

**Issue by erdanieee** [caseyscarborough/keylogger#12]
The keylogger works correctly except for user/password. For example, if you use Safari/firefox to log in your email account, the user/password is not recorded. The same for keychain password and other programs...

**Comment by ghostlymedic** [comment]
Same issue, then I found the answer/reason it's not possible in a closed issue. Reference [Issue #3](https://github.com/caseyscarborough/keylogger/issues/3)

**Comment by caseyscarborough** [comment]
Duplicate of #3.
