### ISSUE TITLE
Command key recording as "aaa"

### ISSUE THREAD

**Issue by ghostlymedic** [caseyscarborough/keylogger#13]
When the commend or apple key is used, it records as "aaa" in the log file. Is there a way to have it recorded as [cmd] to be in line with how the other keys record?

**Comment by caseyscarborough** [comment]
I can't seem to reproduce this... They print `[left-cmd]` and `[right-cmd]` for the left and right command keys for me on OS X 10.10 and 10.11. Are you using an alternate keyboard layout?
