### ISSUE TITLE
Keylogger not working when using it from script

### ISSUE THREAD

**Issue by pranav18** [caseyscarborough/keylogger#16]
Hello,

I am using keylogger for my custom daemon.

Below is a step that I am doing to work with keylogger.

1. Copy the keylogger in custom path i.e. /usr/local/CustomFolderName.
2. Using thing command to start service of keylooger. i.e. 
sudo  /usr/local/CustomFolderName/keylogger.
3. It starts logging the keyboard pressed the button but the problem is it's only capturing special key i.e. Alt,Ctrl, Shift.

Can you please let me know where I am doing wrong?

When I am trying to access the package from the terminal than all things work well.

**Comment by pranav18** [comment]
is there any support for keylogger?

**Comment by wolfiex** [comment]
Replication of this on OS Sierra, 10.12.3!

**Comment by wolfiex** [comment]
See issue #4 ,
Running with sudo or using make autorun fixes this for me .

**Comment by caseyscarborough** [comment]
Thanks @wolfiex, you are correct. `sudo` is required and the README has been updated.
