### ISSUE TITLE
Readme does not specify how to run in the background

### ISSUE THREAD

**Issue by olivertappin** [caseyscarborough/keylogger#17]
The README.md doesn't specifically say how you're able to run this command in the background. This works fine during startup, but not necessary how to run it without restarting.

Raising this issue in anticipation of a pull request.

**Comment by hjhart** [comment]
The command you would run to run this in the background is `sudo launchctl load /Library/LaunchDaemons/keylogger.plist`

**Comment by olets** [comment]
I think it's reasonable to not explicitly point this out in the readme. That's a question about how to run `plist`ed scripts in the background in macOS, not a question of how to use `keylogger`; the readme can't cover every possible use case and shouldn't attempt to

**Comment by caseyscarborough** [comment]
You can run it in the background without restarting with `./keylogger &! exit`.

If you want to run it with launchctl there is apparently a `launchctl kickstart` command that will allow you to do so but I haven't tested it, [more details here](https://serverfault.com/a/947469/948832).
