### ISSUE TITLE
Root privileges required

### ISSUE THREAD

**Issue by stefarossi** [caseyscarborough/keylogger#2]
I tried running this application on OS X 10.10 Yosemite, but it only logs "modifiers", such as "[ctrl][option][cmd][shift]". No other key is logged. Running it with sudo, though, makes it able to log all the keys.
Is there any other way to run it in userspace?

Thank you for sharing your code!

**Comment by heavyk** [comment]
just ran into this. according to http://www.cocoabuilder.com/archive/cocoa/242438-trouble-with-event-taps.html this is intended behaviour. you should enable assistive devices for your app . maybe that'll help.

fortunately, my keylogger is for my own keystrokes, so running as root isn't a problem :)

cheers

**Comment by caseyscarborough** [comment]
See #4.
