### ISSUE TITLE
make fail - load issue

### ISSUE THREAD

**Issue by clm-github** [caseyscarborough/keylogger#20]
hi.  thanks for this great code.  trying to make, i get the message:
sh:>make && make install
gcc keylogger.c -framework ApplicationServices -framework Carbon -o keylogger
ld: can't write output file: keylogger for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [all] Error 1

am using admin account...   osx 10.9.5          hmmmmmm.  it almost looks like the kind of error you'd get if trying to use something designed for the pc, although that would be a million errors i guess...    i went to the dir /usr/local/bin/ and created keylogger to see if that would help... no go.

**Comment by caseyscarborough** [comment]
It requires `sudo` to be ran otherwise you will get this error. The README has since been updated to include the `sudo` requirement.
