### ISSUE TITLE
Run on startup for user,  not system

### ISSUE THREAD

**Issue by snoblenet** [caseyscarborough/keylogger#27]
I've created a temporary account on a borrowed computer.
I want to log my own key strokes to diagnose a problem.
I don't want to log key strokes on any other account.
If I run `sudo make startup`, will it start and run in my temporary account only?
Thanks.

**Comment by Joshfindit** [comment]
According to the documentation, `sudo make startup` starts it for everyone.

It should be easy enough to simply run the binary when you log in using startup scripts, a launch daemon, some other standard method, or possibly even the login items control panel.

**Comment by caseyscarborough** [comment]
There are likely a few ways to accomplish this, but [here is a list of options](https://superuser.com/questions/229773/run-command-on-startup-login-mac-os-x).
