### ISSUE TITLE
ERROR: Unable to create event tap.

### ISSUE THREAD

**Issue by Alino** [caseyscarborough/keylogger#28]
I am getting this error on MacOS Mojave 10.14.4 
is there a fix?

**Comment by nmcc1212** [comment]
Same

**Comment by Quotz** [comment]
Same

**Comment by Quotz** [comment]
Solved it. Go to Settings -> Security & Privacy -> Accessibility and tick Terminal. Now run the command again

**Comment by jmourelos** [comment]
In my case it was Settings -> Security -> Privacy -> Accessibility -> Terminal

**Comment by caseyscarborough** [comment]
Thanks everyone, I added a note to the README about this.
