### ISSUE TITLE
Unable to compile for architecture x86_64

### ISSUE THREAD

**Issue by BimmerBass** [caseyscarborough/keylogger#29]
When i try to directly compile the keylogger.c program, i get the following error:
`<hostname>:keylogger <username>$ gcc keylogger.c
Undefined symbols for architecture x86_64:
  "_CFMachPortCreateRunLoopSource", referenced from:
      _main in keylogger-d948c0.o
  "_CFRunLoopAddSource", referenced from:
      _main in keylogger-d948c0.o
  "_CFRunLoopGetCurrent", referenced from:
      _main in keylogger-d948c0.o
  "_CFRunLoopRun", referenced from:
      _main in keylogger-d948c0.o
  "_CGEventGetIntegerValueField", referenced from:
      _CGEventCallback in keylogger-d948c0.o
  "_CGEventTapCreate", referenced from:
      _main in keylogger-d948c0.o
  "_CGEventTapEnable", referenced from:
      _main in keylogger-d948c0.o
  "_kCFAllocatorDefault", referenced from:
      _main in keylogger-d948c0.o
  "_kCFRunLoopCommonModes", referenced from:
      _main in keylogger-d948c0.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by caseyscarborough** [comment]
Compiling this project requires additional flags, you can't just run `gcc keylogger.c`. You will either need to run `make` or include the `-framework ApplicationServices -framework Carbon` flags.
