### ISSUE TITLE
Broken in 10.10.x

### ISSUE THREAD

**Issue by toddkaufmann** [caseyscarborough/keylogger#4]
Does this work in Yosemite?  I don't get any errors, but this is all I get:

```
Keylogging has begun.
Tue Feb 23 18:52:01 2016

[ctrl][ctrl][ctrl][ctrl][option][option][ctrl][ctrl][ctrl][ctrl][option][option][ctrl][ctrl][option][option]
```

and there should be other keys in there besides modifier keys.

Are all keys now secure events ?

**Comment by toddkaufmann** [comment]
Update:  it does work for other programs besides Terminal.app (e.g. Chrome and Aquamacs).
However, I am mostly interested in Terminal.  Would iterm be any different ?

I did get logKext (binary release) to work
(you just need to chown the plist file to root to get 'launchctl load' to accept it).

**Comment by dineshappavoo** [comment]
@toddkaufmann  I am running in Yosemite. It does not even work in Terminal. Every key press goes to keycode 59
[ctrl][ctrl][ctrl][ctrl][option][option][ctrl]. 

Did you get any workaround. Or is there any other package for keylogging in OSX?

**Comment by onionyst** [comment]
I'm in El Capitan, and it happened when I tried to compile it into another name. But with the original 'key logger', it was okay up to now.

**Comment by JamesMarino** [comment]
Running the executable as root seems to work, I'm on 10.11.4, working in Terminal to @dineshappavoo

**Comment by kevinsimper** [comment]
It works fine for me as well on El Capitan

**Comment by caseyscarborough** [comment]
It appears that non-modifier keys now require root privileges (just tested on Yosemite and El Capitan). Is it working for anyone without root privileges?

**Comment by toddkaufmann** [comment]
Actually, it does work for me (as root).
There are a few things going on which confused me (at first--expecting it to 'just work'--and later, with intermittent working).  I will try to quickly in limited time enumerate...   

1.  first time I probably did not run as root ?
2.  wondered why the launchd service didn't 'take', and later determined it was because the .plist file wasn't owned by root; afterwards, it would load.
3.  found it would be running--ie, actively logging--after a reboot, but then quit.  Found if I restarted it (with "launchctl stop com.fsb.logKext") it would be logging again.  At least, until it wasn't logging any more.
At first I thought it was when it went to sleep, but it still logs (sometimes).
Then I thought it stopped after the log in screen came up, but it still logs.

I am determining this after the fact from the modification time of the file --

     while true; do ls -l /Library/Preferences/com.fsb.logKext; sleep 600; done &

I have not yet tried to correlate this with any other events or messages in /var/log/system.log etc.

A real-time debug (non-secure) just-print-keys-to-stdout mode would be useful
(I could ssh in, run and display remotely).

I could test more later.  Actually I'd love to be able to build it myself with Xcode.  
I was able to load it in, get OpenSSL, ...  but then got lost.

**Comment by dkarter** [comment]
I can confirm it works on El Capitan with sudo.

**Comment by olets** [comment]
Confirming for Sierra

**Comment by dontsovcmc** [comment]
Yosemite 10.10.3
without sudo only modifier keys
with sudo both modifiers and characters

**Comment by wolfiex** [comment]
I believe running it at startup `sudo make startup` and then restarting functions as if it was run as sudo on Sierra.

**Comment by caseyscarborough** [comment]
Running with `sudo` is the correct solution.
