### ISSUE TITLE
Modifier keys log on keydown and keyup

### ISSUE THREAD

**Issue by caseyscarborough** [caseyscarborough/keylogger#8]
Currently modifier keys log on keydown and keyup events. For example, pressing the left shift once will result in the following in the log file:

```
[left-shift][left-shift]
```

There doesn't seem to be an obvious way to fix it, as the modifier keys seem to be triggered on the `kCGEventFlagsChanged` event type, not on `kCGEventKeyDown` or `kCGEventKeyUp`.

**Comment by RSully** [comment]
IMO it would be even more helpful if it said "[left-shift down][left-shift up]" so in the case of uppercase words you know the begin/end

**Comment by mattalexander-pantheon** [comment]
2016? I think I'll uninstall rather than hold my breath.

**Comment by caseyscarborough** [comment]
Resolved.

**Comment by caseyscarborough** [comment]
@mattalexander-pantheon Thanks for the bump. I've have left this unmaintained for a long time, but I've just done some much needed house cleaning. Hopefully it meets your needs now.

**Comment by RSully** [comment]
Any thoughts on handling up/down events for something like shift? Hard to know which letters are capitalized if we don't know when it was released

**Comment by caseyscarborough** [comment]
@RSully I made an update tonight that applies the shift key to the output of the log file, so if the shift key is held it will show the proper special character or capital letter.

**Comment by caseyscarborough** [comment]
@RSully I made an update tonight that applies the shift key state to the output of the log file. If the shift key is held it will show the proper special character or capital letter that corresponds to the combination of the two keys.

**Comment by RSully** [comment]
Cool, glad to see some attention here. With that said, I think the current implementation doesn't lend itself too well to supporting international keyboard layouts in the future (?)

**Comment by andmis** [comment]
You can figure out whether the key event was an up or down event by inspecting the flags of the event @caseyscarborough :
```c
    // In CGEventCallback
    printf("%llu\n", CGEventGetFlags(event));
```
